### ISSUE TITLE
ADH configuration

### ISSUE THREAD

**Issue by Pr0mises** [iganeshk/adwireguard-dark#1]
How did you configure ADH?
I used your docker-compose file did /install left everything at default and using all interfaces. Opened wireguard added a client. Handshake is working, no internet connection and no requests in adguard seen.

my docker-compose file:
```
version: "3.8"

services:
  adwireguard:
    container_name: adwireguard
    # image: ghcr.io/iganeshk/adwireguard-dark:latest
    image: iganesh/adwireguard-dark:latest
    restart: unless-stopped
    ports:
      - '55:53'           # AdGuardHome DNS Port
      - '3001:80'       # Default Address AdGuardHome WebUI
      - '853:853'         # DNS-TLS
      - '51820:51820/udp' # wiregaurd port
      - '51822:51821/tcp' # wg-easy webUI
    environment:
        # WG-EASY ENVS
      - WG_HOST=secret
      - PASSWORD=secret
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.8.3.x
      - WG_DEFAULT_DNS=10.8.4.2
      - WG_MTU=1420
      - WG_ALLOWED_IPS=0.0.0.0, ::/0
    volumes:
        # adguard-home volume
      - "./adguard/work:/opt/adwireguard/work"
      - "./adguard/conf:/opt/adwireguard/conf"
        # wg-easy volume
      - './wireguard:/etc/wireguard'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1    # Disable IPv6
    networks:
      vpn_net:
        ipv4_address: 10.8.4.2

networks:
  vpn_net:
    ipam:
      driver: default
      config:
        - subnet: 10.8.4.0/24
```

**Comment by gyaneesh** [comment]
I found ADH working with listening on etho(docker)/wget adapter, Everything else is default. Did you try bash'ing into your container and see if there's services listening on right ports and verify network?

**Comment by gyaneesh** [comment]
I did further updates to the image. If you're able to pull the latest, let me know if you're able to attach to the container and check network connectivity within the container.
Client's from within the container and outside should be able to use port 53 and AGH should report the right IP. Also I found out that if you're using wg tunnel in Android, private dns will override your DNS set in the tunnel

**Comment by Pr0mises** [comment]
I did use your new image. Setup adh to listen on eth0 on webinterface and dns. Internet within the container is working, nslookup google.com 10.8.4.2 is working also. 
dig -b 10.8.4.1  google.com
and 
dig -b 10.8.3.1  google.com
are working aswell.
Using wireguard on android requests are coming through (i see them in adh) but no internet connection. What allowed IPs did you use?

Also I only want to use adh with wireguard, no connection from outside

**Comment by gyaneesh** [comment]
>What allowed IPs did you use?

0.0.0.0/0

> Also I only want to use adh with wireguard, no connection from outside

Ah, well, you wouldn't want to use expose any ports besides the wg-easy! I currently use dns-tls, it works neat with wg-clients and adh clientIDs.

**Comment by Pr0mises** [comment]
Well I'm unsure then why it's not working for me. You do have internet?

**Comment by gyaneesh** [comment]
I've deployed this image on 3x amd64 instance and an arm7, so far no problems!

**Comment by gyaneesh** [comment]
Were you able to solve this? Can I also know what client you are using for Android? I'm running [VPN Client Pro](https://play.google.com/store/apps/details?id=it.colucciweb.vpnclientpro)

**Comment by Pr0mises** [comment]
Well yes I guess? Was on vacation just pulled the new image now it's working out of sudden. Didn't change anything, even same config + users. I'm using the default wireguard app

**Comment by sypion** [comment]
Hello! I'm having a similar issue, where AGH and Wireguard are running, however, Wireguard client connects but does not load anything nor show up in AGH query log.

My Docker compose:
```
version: "3.8"

services:
  adwireguard:
    container_name: adwireguard
    # image: ghcr.io/iganeshk/adwireguard-dark:latest
    image: iganesh/adwireguard-dark:latest
    restart: unless-stopped
    ports:
      - '53:53'           # AdGuardHome DNS Port
      - '3000:3000'       # Default Address AdGuardHome WebUI
      - '853:853'         # DNS-TLS
      - '51823:51820/udp' # wiregaurd port
      - '51821:51821/tcp' # wg-easy webUI
    environment:
        # WG-EASY ENVS
      - WG_HOST=[redacted]
      - PASSWORD=[redacted]
      - WG_PORT=51823
      - WG_DEFAULT_ADDRESS=10.10.11.3
      - WG_DEFAULT_DNS=192.168.4.110
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_POST_UP=iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      - WG_POST_DOWN=iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      - WG_MTU=1420
    volumes:
        # adguard-home volume
      - '/home/user/agh/work:/opt/adwireguard/work'
      - '/home/user/agh/conf:/opt/adwireguard/conf'
        # wg-easy volume
      - '/home/user/wireguard:/etc/wireguard'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1    # Disable IPv6
    networks:
      vpn_net:
        ipv4_address: 10.10.10.2

networks:
  vpn_net:
    ipam:
      driver: default
      config:
        - subnet: 10.10.10.0/24
```

Not sure what I'm missing. Any help would be appreciated :)
