### ISSUE TITLE
Doesn`t work at all.

### ISSUE THREAD

**Issue by dm9tr0** [iganeshk/adwireguard-dark#3]
Usual wireguard image 'https://lscr.io/linuxserver/wireguard:latest' works awesome, your implementation doesn`t work at all.
Have you tried to run it not locally?!

**Comment by gyaneesh** [comment]
I have deployed it over multiple instances. Here's one of them
```
root@slice:~# cat /etc/debian_version 
11.6
root@slice:~# ufw --version
ufw 0.36
Copyright 2008-2015 Canonical Ltd.
root@slice:~# docker --version
Docker version 20.10.22, build 3a2c30b
root@slice:~# docker compose version
Docker Compose version v2.14.1
root@slice:~# ip route
default via 1x.x.3.1 dev ens3 
10.4.4.0/24 dev br-94e7696dffcc proto kernel scope link src 10.4.4.1 
1x.x.3.0/24 dev ens3 proto kernel scope link src 1x.x.3.244 
172.17.0.0/16 dev docker0 proto kernel scope link src 172.17.0.1 linkdown 
root@slice:~# cat adwireguard-dark/docker-compose.yml 
version: "3.8"

services:
  adwireguard:
    container_name: adwireguard
    image: iganesh/adwireguard-dark:latest
    restart: unless-stopped
    ports:
      - '8191:8191'  # WebUI
      - '3000:3000'  # WebUI-Install
      - '53:53'           # AdGuardHome DNS Port
      - '853:853'         # DNS-TLS
      - '51820:51820/udp' # wiregaurd port
      - '8192:51821/tcp' # wg-easy webUI
    environment:
        # WG-EASY ENVS
      - WG_HOST=PublicIP
      - PASSWORD=passwordHere
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.4.5.x
      - WG_DEFAULT_DNS=10.4.4.2
      - WG_MTU=1420
    volumes:
        # adguard-home volume
      - './adguard/work:/opt/adwireguard/work'
      - './adguard/conf:/opt/adwireguard/conf'
        # wg-easy volume
      - './wireguard:/etc/wireguard'
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1    # Disable IPv6
    networks:
      vpn_net:
        ipv4_address: 10.4.4.2

networks:
  vpn_net:
    ipam:
      driver: default
      config:
        - subnet: 10.4.4.0/24
          gateway: 10.4.4.1
root@slice:~# 
```
```
root@lux:~# netstat -tunlp
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:3000           0.0.0.0:*               LISTEN      11326/docker-proxy  
tcp        0      0 0.0.0.0:8192           0.0.0.0:*               LISTEN      11286/docker-proxy  
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      5780/nginx: master  
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      11386/docker-proxy  
tcp        0      0 0.0.0.0:853             0.0.0.0:*               LISTEN      11366/docker-proxy  
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1002/sshd: /usr/sbi 
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      5780/nginx: master  
tcp        0      0 0.0.0.0:8191            0.0.0.0:*               LISTEN      11346/docker-proxy  
tcp6       0      0 :::3000                :::*                    LISTEN      11331/docker-proxy  
tcp6       0      0 :::8192                :::*                    LISTEN      11291/docker-proxy  
tcp6       0      0 :::53                   :::*                    LISTEN      11391/docker-proxy  
tcp6       0      0 :::853                  :::*                    LISTEN      11371/docker-proxy  
tcp6       0      0 :::22                   :::*                    LISTEN      1002/sshd: /usr/sbi 
tcp6       0      0 :::8191                 :::*                    LISTEN      11351/docker-proxy  
udp        0      0 0.0.0.0:68              0.0.0.0:*                           394/dhclient        
udp        0      0 0.0.0.0:51820           0.0.0.0:*                           11306/docker-proxy  
udp6       0      0 :::51820                :::*                                11311/docker-proxy
```
