### ISSUE TITLE
Can't access to any website even it seems it's working.

### ISSUE THREAD

**Issue by emailforos** [iganeshk/adwireguard-dark#9]
Hi.

I deployed your docker in a free Oracle VPS and I have a problem. Adguard is receiving the DNS queries but my cell phone is not receiving the answer so it doesn't enter to any website.

My setup is:

```
adwireguard:
    container_name: adwireguard
    # image: ghcr.io/iganeshk/adwireguard-dark:latest
    image: iganesh/adwireguard-dark:latest
    restart: unless-stopped
    ports:
      - '53:53'           # AdGuardHome DNS Port
      - '3000:3000'       # Default Address AdGuardHome WebUI
      - '853:853'         # DNS-TLS
      - '51820:51820/udp' # wiregaurd port
      - '51821:51821/tcp' # wg-easy webUI
    environment:
        # WG-EASY ENVS
      - WG_HOST=xxx.duckdns.org
      - PASSWORD=${PASS}
      - WG_PORT=51820
      - WG_DEFAULT_ADDRESS=10.10.11.x
      - WG_DEFAULT_DNS=${APP_ADGUARD_IP}
      - WG_MTU=1420
      - WEBUI_HOST=0.0.0.0 # Change this to allow binding to other than 0.0.0.0 port
    volumes:
        # adguard-home volume
      - ${HOME}/docker/adguard/work:/opt/adwireguard/work
      - ${HOME}/docker/adguard/confdir:/opt/adwireguard/conf
        # wg-easy volume
      - ${HOME}/docker/wireguard:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1    # Disable IPv6
    networks:
      default:
        ipv4_address: ${APP_ADGUARD_IP}`
```

And I'm able to reach adguard and wireguard webui.

In adguard I see that there are queries:
![imagen](https://github.com/iganeshk/adwireguard-dark/assets/20602874/67a74452-df0d-478a-a9c1-73341bc17a35)

And in wireguard, there is up/down changes:
![imagen](https://github.com/iganeshk/adwireguard-dark/assets/20602874/68a2efac-0687-462b-abb3-ca5e7e17c59a)

Before I was using adguard and wg-easy "standard" docker installation but I was looking for a solution to be able to see all the clients IP in adguard to customize the filtering (some for my wife and I, some for my kids).

I tried somethings but I'm noob in networks setup.

Any idea of what I can check or try?

Thank you in advance.
